[project]
name = "minifydemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.9",
    "django-minify-html>=1.14.0",
    "gunicorn>=21.0.0",
]
